server:
  port: 9006
spring:
  application:
    name: micro-spit #吐槽服务
  data:
    mongodb:
      host: 192.168.0.104
      database: spit
  redis:
    host: 192.168.0.104
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true
